### ISSUE TITLE
KeyError when importing data

### ISSUE THREAD

**Issue by itsjavi** [ccev/pogodatapy#10]
hi, it seems that the module has an error in this line:

```
File /usr/local/lib/python3.9/site-packages/pogodata/pogodata.py:417, in PogoData.__make_mon_list(self)
    414 if "temporaryEvolution" in evo_raw:
    415     continue
    416 evo = self.get_mon(
--> 417     template=evo_raw.get("form", evo_raw["evolution"])
    418 )
    419 mon.evolutions.append(evo)

KeyError: 'evolution'
```

this is my code:

```py
from pogodata import PogoData
data = PogoData(language="english")
```

**Comment by ccev** [comment]
Hi. Sorry, this project is no longer maintained. Seems like I forgot to archive it.

This error is happening because something in the gamemaster isn't like it was when I made the parser about a year ago. It's best to debug and fix this yourself if you're looking to use this.  Perhaps [this master file generator](https://github.com/WatWowMap/Masterfile-Generator) could also be helpful instead.
